In [ ]:
#Titulo: IA y Big Data - Práctica Instagram
#Fecha: 25/05/2026
#Autor: Luis Alberto García Leza

In [2]:
# IMPORTAMOS LIBRERÍAS
import pandas as pd
import random

In [4]:
# DATOS BASE
datosInstagram = {
    "influencer": [
        "ana_travel",
        "luis_beach",
        "cancun_life",
        "mexico_vibes",
        "playas_mx",
        "travel_queen"
    ],

    "tipo_post": [
        "turismo",
        "playa",
        "lifestyle",
        "comida",
        "hotel",
        "aventura"
    ],

    "fecha": [
        "2026-01-10",
        "2026-02-14",
        "2026-03-20",
        "2026-04-15",
        "2026-05-18",
        "2026-06-01"
    ]
}

In [5]:
# CREAR DATAFRAME BASE
dfInstagram = pd.DataFrame(datosInstagram)

In [6]:
# MOSTRAR DATOS BASE
dfInstagram

     influencer  tipo_post       fecha
0    ana_travel    turismo  2026-01-10
1    luis_beach      playa  2026-02-14
2   cancun_life  lifestyle  2026-03-20
3  mexico_vibes     comida  2026-04-15
4     playas_mx      hotel  2026-05-18
5  travel_queen   aventura  2026-06-01

In [7]:
# CANTIDAD DE REGISTROS
cantidad = 1000000

In [8]:
# GENERAR BIG DATASET
dfBigData = pd.DataFrame({

    "influencer": [
        random.choice(dfInstagram["influencer"])
        for _ in range(cantidad)
    ],

    "likes": [
        random.randint(100, 50000)
        for _ in range(cantidad)
    ],

    "comentarios": [
        random.randint(10, 5000)
        for _ in range(cantidad)
    ],

    "fecha": [
        random.choice(dfInstagram["fecha"])
        for _ in range(cantidad)
    ],

    "tipo_post": [
        random.choice(dfInstagram["tipo_post"])
        for _ in range(cantidad)
    ]

})

In [9]:
# MOSTRAR LAS PRIMERAS FILAS
dfBigData.head()

     influencer  likes  comentarios       fecha tipo_post
0   cancun_life  16649          824  2026-01-10    comida
1    ana_travel  48028         1344  2026-02-14  aventura
2  mexico_vibes  40224         1150  2026-04-15  aventura
3   cancun_life  26405         1329  2026-03-20     hotel
4  travel_queen  49881         4948  2026-04-15     playa

In [10]:
# TAMAÑO DEL DATAFRAME
dfBigData.shape

(1000000, 5)

In [11]:
# TIPOS DE DATOS
dfBigData.dtypes

influencer     object
likes           int64
comentarios     int64
fecha          object
tipo_post      object
dtype: object

In [12]:
# MEMORIA UTILIZADA
dfBigData.memory_usage(deep=True).sum() / 1024**2

np.float64(181.51604461669922)

In [13]:
dfBigData["likes"].mean()

np.float64(25036.424733)

In [14]:
# Influencer con más likes promedio
dfBigData.groupby("influencer")["likes"].mean()

influencer
ana_travel      25000.294808
cancun_life     25041.392758
luis_beach      25051.307238
mexico_vibes    25012.507903
playas_mx       25043.858439
travel_queen    25069.250719
Name: likes, dtype: float64

In [15]:
#Tipo de post con más comentarios
dfBigData.groupby("tipo_post")["comentarios"].mean()

tipo_post
aventura     2507.498645
comida       2502.769353
hotel        2511.214525
lifestyle    2502.337569
playa        2507.804195
turismo      2502.023434
Name: comentarios, dtype: float64

In [16]:
#Total de publicaciones por tipo
dfBigData["tipo_post"].value_counts()

tipo_post
lifestyle    166982
hotel        166834
turismo      166763
aventura     166746
playa        166599
comida       166076
Name: count, dtype: int64

In [17]:
#Top 10 publicaciones con más likes
dfBigData.sort_values(by="likes", ascending=False).head(10)

          influencer  likes  comentarios       fecha  tipo_post
111696    ana_travel  50000          640  2026-01-10      hotel
519276   cancun_life  50000         1727  2026-06-01  lifestyle
680508  travel_queen  50000         4387  2026-02-14  lifestyle
438037  mexico_vibes  50000         2000  2026-03-20    turismo
575305     playas_mx  50000         2988  2026-04-15  lifestyle
766216    ana_travel  50000         2068  2026-03-20     comida
263786     playas_mx  50000         3624  2026-02-14      playa
429431    luis_beach  50000         1597  2026-01-10    turismo
238422     playas_mx  50000          244  2026-03-20     comida
834978  travel_queen  50000         4921  2026-05-18      playa